default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: db
  username: postgres
  password:
development:
  <<: *default
  database: mfeito_development
test:
  <<: *default
  database: mfeito_test
production:
  <<: *default
  host: <%= ENV['MFEITO_DATABASE_HOST'] %>
  database: <%= ENV['MFEITO_DATABASE_DATABASE'] %>
  username: <%= ENV['MFEITO_DATABASE_USERNAME'] %>
  password: <%= ENV['MFEITO_DATABASE_PASSWORD'] %>

